name: smallbytes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^12.0.4
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  curved_navigation_bar: ^1.0.6
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.2
  razorpay_flutter: ^1.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login_illu.svg

